# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install server dependencies
      run: npm i
    - name: Deloy to host
      uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "academy-for-test" #Must be unique in Heroku
          heroku_email: "lequanghai540@gmail.com"
          procfile: "web: npm start"
      env:
          HD_DB_HOST: us-cdbr-east-04.cleardb.com
          HD_DB_PORT: 3306
          HD_DB_USER: ${{secrets.DB_USER}}
          HD_DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          HD_DB_NAME: heroku_2918cd1316c63a1
          HD_NODE_ENVIROMMENT: pro
          HD_HOST:  ${{secrets.HOST_NAME}}
          HD_HOST_NAME: ${{secrets.HOST_NAME}}
          HD_URL: ${{secrets.HOST_NAME}}
    - name: Katalon Report Uploader
      uses: katalon-studio/report-uploader@v0.0.8
      env:
          PASSWORD: 989c890f-a904-478c-90a4-14235033446b
          PROJECT_ID: 149338
          TYPE: katalon
          REPORT_PATH: AutoReport
      
    
