# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install server dependencies
      run: npm i
    - name: Deloy to staging
      uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "academy-for-test" #Must be unique in Heroku
          heroku_email: "lequanghai540@gmail.com"
          procfile: "web: npm start"
      env:
          HD_DB_HOST: us-cdbr-east-04.cleardb.com
          HD_DB_PORT: 3306
          HD_DB_USER: ${{secrets.DB_USER}}
          HD_DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          HD_DB_NAME: heroku_2918cd1316c63a1
          HD_NODE_ENVIROMMENT: pro
          HD_HOST:  ${{secrets.HOST_NAME}}
          HD_HOST_NAME: ${{secrets.HOST_NAME}}
          HD_URL: ${{secrets.HOST_NAME}}
    - name: Send mail
      if: always()
      uses: dawidd6/action-send-mail@v2
      with:
          # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
          # user credentials
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          # email subject
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          # email body as text
          body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
          # comma-separated string, send email to
          to: lequanghai540@gmail.com, mailinhdong@gmail.com, meokg456@gmail.com, nguyentonhi199@gmail.com
          # from email name
          from: Quang Hai
          
  automationtest:
  
    needs: build
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v2.1
      with:
          version: '7.5.5'
          projectPath: '${{ github.workspace }}/automationTest'
          args: '-noSplash -retry=0 -browserType=Chrome -statusDelay=15 -testSuitePath="Test Suites/DemoTestSuite" -apiKey= ${{ secrets.KATALON_API_KEY }} --config -webui.autoUpdateDrivers=true'
    - name: Send mail
      if: always()
      uses: dawidd6/action-send-mail@v2
      with:
          # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
          # user credentials
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          # email subject
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          # email body as text
          body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
          # comma-separated string, send email to
          to: lequanghai540@gmail.com, mailinhdong@gmail.com, meokg456@gmail.com, nguyentonhi199@gmail.com
          # from email name
          from: Quang Hai

    
